# remove client keys 
--- 
- hosts: vpn
  vars:
      clients:
          #        - client1
        - client2

  tasks:

    - name: remove clients keys                                                                                                                
      file: path=/etc/openvpn/keys/{{ item }}.key state=absent                                                                                        
      with_items:                                                                                                                                     
        - "{{ clients }}"

    - name: remove clients csr
      file: path=/etc/openvpn/keys/{{ item }}.csr state=absent                                                                                        
      with_items:                                                                                                                                     
        - "{{ clients }}"

    - name: remove clients configs
      file: path=/etc/openvpn/{{ item }}.ovpn state=absent
      with_items:
          #- client1-{{inventory_hostname}} 
          - client2-{{inventory_hostname}}


    - name: revoke user certs from servers
      environment:
            EASY_RSA: /etc/openvpn/
            OPENSSL: openssl
            PKCS11TOOL: pkcs11-tool
            PKCS11_MODULE_PATH: "dummy"
            PKCS11_PIN: "dummy"
            KEY_CONFIG: /etc/openvpn/openssl-1.0.0.cnf
            KEY_DIR: /etc/openvpn/keys
            KEY_SIZE: 2048
            CA_EXPIRE: 3650
            KEY_EXPIRE: 3650
            KEY_COUNTRY: "US"
            KEY_PROVINCE: "CA"
            KEY_CITY: "SanFrancisco"
            KEY_ORG: "Fort-Funston"
            KEY_EMAIL: "me@myhost.mydomain"
            KEY_OU: "MyOrganizationalUnit"
            KEY_NAME: "EasyRSA"

      shell: /etc/openvpn/revoke-full {{ item }}
      with_items: 
        - "{{ clients }}"
      ignore_errors: yes

      #    - name: remove clients certificate                                                                                                                
      #      file: path=/etc/openvpn/keys/{{ item }}.crt state=absent                                                                                        
      #      with_items:                                                                                                                                     
      #        - "{{ clients }}"    
    - name: restart ovpn
      service: name=openvpn state=restarted
