# install easy-rsa and placed for the right place
 - name: yum install easy-rsa                                                                                                                      
   yum: name=easy-rsa  state=present

 - name: copy easy-rsa
   raw: cp -R /usr/share/easy-rsa/2.0/* /etc/openvpn

 - name: create index.txt
   file: path={{openvpn_key_dir}}/index.txt state=touch

 - name: create index.txt.attr
   file: path={{openvpn_key_dir}}/index.txt.attr state=touch

 - name: link ca.key to ca-key.pam
   raw: ln /etc/openvpn/keys/ca-key.pem  /etc/openvpn/keys/ca.key
